apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-code-with-quarkus-ufxa
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-code-with-quarkus-ufxa
    app.kubernetes.io/part-of: quarkus
  name: devfile-sample-code-with-quarkus-ufxa
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: devfile-sample-code-with-quarkus-ufxa
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: devfile-sample-code-with-quarkus-ufxa
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-wjrc-tenant/quarkus/devfile-sample-code-with-quarkus-ufxa@sha256:8819722c6a0f6b9a7b8a269dc7f6e4f6bca0899c494fa6593fa11bd201a5d442
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
